// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWm9oy5RMcDjPBGKtAi4FNREVc8xDMY8E',
    appId: '1:986161942967:web:99016fe983801f4eee9832',
    messagingSenderId: '986161942967',
    projectId: 'nacho-momma',
    authDomain: 'nacho-momma.firebaseapp.com',
    storageBucket: 'nacho-momma.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7D5XUv3bhqvB5V1LlWwwSEoNHVmsKpho',
    appId: '1:986161942967:android:e2392057cc3332f8ee9832',
    messagingSenderId: '986161942967',
    projectId: 'nacho-momma',
    storageBucket: 'nacho-momma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInvbN8SfqtXLKeJ-OIRKZ4ivfwb-3fTE',
    appId: '1:986161942967:ios:37a237775492856cee9832',
    messagingSenderId: '986161942967',
    projectId: 'nacho-momma',
    storageBucket: 'nacho-momma.appspot.com',
    iosBundleId: 'com.example.projectBlueChip',
  );
}
